### ISSUE TITLE
Re-jigger and enhance MDN annotations

### ISSUE THREAD

**Issue by sideshowbarker** [whatwg/wattsi#110]
- [x] Add indicators to mark features that require setting a user preference or runtime flag (#108)
- [x] Add indicators for features with less than two implementations in current engines (#109)
- [x] Reformat to eliminate (too-tiny) toggle widget; instead just click **MDN** to expand (#114)
- [x] Reformat to not require additional click on disclosure triangle for expanding support table (eliminate use of \<details>/\<summary> within the anno) (#114)
- [x] Reformat to match the same presentation we use for MDN annos generated by Bikeshed (#114)
- [x] Reorder browser lists w/ Firefox/Safari/Chrome grouped first — at top — and then other browsers grouped after; with lines/\<hr>’s/rules between to demarcate groupings (#114)
- [x] Show version ranges for removed features (*added – removed*), as in Bikeshed annos (#114)
- [x] Handle nonconforming support cases (partial and prefixed implementations)  (#114)
- [x] Don’t show *"No support data"* nor no-support icon for support-info-missing cases (#115)

**Comment by domenic** [comment]
This might be all done now, I think!

**Comment by domenic** [comment]
Hmm, maybe not the toggle widget.
